first_time_login.settings:
  type: config_object
  label: 'FirstTimeLogin Settings'
  mapping:
    first_time_login_config_days:
      type: text
      label: 'Enter the number of days.'
    first_time_login_new_user_message:
      type: text
      label: 'First Time Login New User Message'
    first_time_login_update_user_message:
      type: text
      label: 'First Time Login Update User Message'
