users_export.settings:
  type: mapping
  label: Settings
  mapping:
    users_export_type:
      type: string
    users_export_date_format:
      type: string
    users_export_filename:
      type: string
    users_export_test_mode:
      type: boolean
    users_export_user_status:
      type: integer
    users_export_last_export_memory:
      type: integer
    users_export_memory_limit:
      type: integer
    users_export_last_export_time:
      type: integer
    users_export_max_execution:
      type: integer
