# Schema for the configuration files of the linkedin_insiths module.
linkedin_insights_tag.settings:
  type: config_object
  label: 'LinkedIn Insights settings'
  mapping:
    user_role_roles:
      type: sequence
      label: 'Roles'
    partner_id:
      type: string
      label: 'Partner ID'
    image_only:
      type: boolean
      label: 'Image only'
